# Generated by Django 4.2.16 on 2025-04-11 07:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CUSTApp', '0003_request_employeeid_request_studentid_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('application_name', models.CharField(max_length=255)),
                ('short_name', models.CharField(max_length=100)),
                ('application_desc', models.TextField()),
                ('status', models.IntegerField(choices=[(1, 'Enabled'), (0, 'Disabled')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('default_responsible_employee', models.ForeignKey(db_column='default_responsible_employee_id', default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('responsible_dept', models.ForeignKey(db_column='responsible_dept_id', on_delete=django.db.models.deletion.CASCADE, to='CUSTApp.department')),
            ],
            options={
                'db_table': 'applications',
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Failed', 'Failed')], default='Pending', max_length=50)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('EmployeeID', models.IntegerField(blank=True, null=True)),
                ('StudentID', models.IntegerField(blank=True, null=True)),
                ('renderedtemplate', models.CharField(blank=True, max_length=10000, null=True)),
                ('applicant', models.ForeignKey(db_column='applicant_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('application', models.ForeignKey(db_column='application_id', on_delete=django.db.models.deletion.CASCADE, to='ApplicationTemplate.applications')),
            ],
            options={
                'db_table': 'request',
            },
        ),
    ]
