# Generated by Django 4.2.16 on 2025-04-11 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApplicationTemplate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='test',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
