# Generated by Django 4.2.16 on 2025-04-11 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ApplicationTemplate', '0002_applications_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applications',
            name='test',
        ),
    ]
