# Generated by Django 4.1.13 on 2025-04-18 04:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApplicationTemplate', '0003_remove_applications_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='request_file',
            field=models.FileField(blank=True, null=True, upload_to='media/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
