# Generated by Django 4.1.13 on 2025-05-04 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApplicationTemplate', '0004_request_request_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
