# Generated by Django 4.1.13 on 2025-05-06 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApplicationTemplate', '0005_alter_request_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
