# Generated by Django 4.1.13 on 2025-05-14 08:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CUSTApp', '0008_alter_users_picture'),
        ('ApplicationTemplate', '0006_request_approved_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='date-time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='guest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guest_reqests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='request',
            name='host_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guest_pass_requests', to='CUSTApp.department'),
        ),
        migrations.AddField(
            model_name='request',
            name='reason',
            field=models.TextField(null=True),
        ),
    ]
