# Generated by Django 4.1.13 on 2025-05-14 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ApplicationTemplate', '0007_request_date-time_request_guest_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='date-time',
            new_name='meeting_date_time',
        ),
    ]
