# Generated by Django 4.1.13 on 2025-05-14 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApplicationTemplate', '0008_rename_date-time_request_meeting_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='request_type',
            field=models.CharField(choices=[('GuestPass', 'Application')], default='Application', max_length=50),
        ),
    ]
