# Generated by Django 4.1.13 on 2025-05-14 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ApplicationTemplate', '0009_request_request_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='application',
            field=models.ForeignKey(blank=True, db_column='application_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='ApplicationTemplate.applications'),
        ),
    ]
