# Generated by Django 4.1.13 on 2025-05-14 08:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ApplicationTemplate', '0010_alter_request_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='applicant',
            field=models.ForeignKey(blank=True, db_column='applicant_id', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
