# Generated by Django 4.1.13 on 2025-06-13 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApplicationTemplate', '0015_rename_checkedin_at_request_vistied_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='expired_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
