# Generated by Django 4.1.13 on 2025-06-13 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApplicationTemplate', '0016_request_expired_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='guest_fcm_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
