# Generated by Django 4.1.13 on 2025-06-13 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ApplicationTemplate', '0017_request_guest_fcm_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='guest_fcm_token',
        ),
    ]
