# Generated by Django 4.1.13 on 2025-08-11 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApplicationTemplate', '0019_request_complain_department_head_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='application_type',
            field=models.CharField(choices=[('General', 'General'), ('Convocation', 'Convocation')], default='General', max_length=50),
        ),
    ]
