# Generated by Django 4.1.13 on 2025-05-12 06:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CUSTApp', '0008_alter_users_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestPassRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('approved', models.BooleanField(default=False)),
                ('date-time', models.DateTimeField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_reqests', to=settings.AUTH_USER_MODEL)),
                ('host_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_pass_requests', to='CUSTApp.department')),
            ],
        ),
    ]
