# Generated by Django 4.1.13 on 2025-05-12 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GuestPass', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='guestpassrequest',
            table='GuestPassRequest',
        ),
    ]
