# Generated by Django 4.1.13 on 2025-05-12 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GuestPass', '0002_alter_guestpassrequest_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='guestpassrequest',
            table='guest_pass_requests',
        ),
    ]
