# Generated by Django 4.1.13 on 2025-05-13 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GuestPass', '0003_alter_guestpassrequest_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestpassrequest',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
