# Generated by Django 4.1.13 on 2025-05-14 08:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CUSTApp', '0008_alter_users_picture'),
        ('GuestPass', '0004_guestpassrequest_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestpassrequest',
            name='date-time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='guestpassrequest',
            name='guest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='guestpassrequest',
            name='host_department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host', to='CUSTApp.department'),
        ),
    ]
