# Generated by Django 4.1.13 on 2025-05-14 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GuestPass', '0005_alter_guestpassrequest_date-time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestpassrequest',
            name='date-time',
            field=models.DateTimeField(),
        ),
    ]
