# Generated by Django 4.1.13 on 2025-05-15 07:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('GuestPass', '0007_alter_guestpassrequest_date-time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guestpassrequest',
            name='host_department',
        ),
        migrations.AddField(
            model_name='guestpassrequest',
            name='host',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='host', to=settings.AUTH_USER_MODEL),
        ),
    ]
