# Generated by Django 4.1.13 on 2025-05-15 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GuestPass', '0008_remove_guestpassrequest_host_department_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GuestPassRequest',
        ),
    ]
