# Generated by Django 4.2.16 on 2025-03-12 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('requested_application', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('letter_type', models.CharField(choices=[('Bona-Fide', 'Bona-Fide Certificate'), ('Fee_Equivalence', 'Fee Equivalence Certificate'), ('English_Proficiency', 'English Proficiency Certificate')], default='Bona-Fide', max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
            options={
                'db_table': 'applications',
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Failed', 'Failed')], default='Pending', max_length=50)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'request',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('uu_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('father_name', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('program_name', models.CharField(blank=True, max_length=255, null=True)),
                ('dept_name', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_type', models.CharField(blank=True, max_length=50, null=True)),
                ('role', models.CharField(blank=True, max_length=50, null=True)),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('otp', models.CharField(blank=True, max_length=10, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('picture', models.CharField(blank=True, max_length=255, null=True)),
                ('cgpa', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('term', models.CharField(blank=True, max_length=10, null=True)),
                ('DoB', models.DateField(blank=True, null=True)),
                ('CNIC', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='TemplateAttributes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('attribute_name', models.CharField(max_length=255)),
                ('attribute_value', models.TextField(blank=True, null=True)),
                ('is_template', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request', models.ForeignKey(db_column='request_id', on_delete=django.db.models.deletion.CASCADE, to='CUSTApp.request')),
            ],
            options={
                'db_table': 'template_attributes',
            },
        ),
        migrations.AddField(
            model_name='request',
            name='applicant',
            field=models.ForeignKey(db_column='applicant_id', on_delete=django.db.models.deletion.CASCADE, to='CUSTApp.users'),
        ),
        migrations.AddField(
            model_name='request',
            name='application',
            field=models.ForeignKey(db_column='application_id', on_delete=django.db.models.deletion.CASCADE, to='CUSTApp.applications'),
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dept_id', models.AutoField(primary_key=True, serialize=False)),
                ('dept_name', models.CharField(max_length=255)),
                ('dept_head', models.ForeignKey(db_column='dept_head_id', on_delete=django.db.models.deletion.CASCADE, to='CUSTApp.users')),
            ],
            options={
                'db_table': 'department',
            },
        ),
        migrations.AddField(
            model_name='applications',
            name='default_responsible_employee',
            field=models.ForeignKey(db_column='default_responsible_employee_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='CUSTApp.users'),
        ),
        migrations.AddField(
            model_name='applications',
            name='responsible_dept',
            field=models.ForeignKey(db_column='responsible_dept_id', on_delete=django.db.models.deletion.CASCADE, to='CUSTApp.department'),
        ),
    ]
