# Generated by Django 4.2.16 on 2025-03-27 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CUSTApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applications',
            old_name='requested_application',
            new_name='application_name',
        ),
        migrations.RemoveField(
            model_name='applications',
            name='letter_type',
        ),
        migrations.RemoveField(
            model_name='templateattributes',
            name='is_template',
        ),
        migrations.RemoveField(
            model_name='templateattributes',
            name='request',
        ),
        migrations.AddField(
            model_name='applications',
            name='application_desc',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applications',
            name='short_name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applications',
            name='status',
            field=models.IntegerField(choices=[(1, 'Enabled'), (0, 'Disabled')], default=1),
        ),
        migrations.AddField(
            model_name='department',
            name='short_name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
