# Generated by Django 4.2.16 on 2025-04-11 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CUSTApp', '0002_rename_requested_application_applications_application_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='EmployeeID',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='StudentID',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='renderedtemplate',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
