# Generated by Django 4.1.13 on 2025-04-16 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CUSTApp', '0005_remove_request_applicant_remove_request_application_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('program_id', models.AutoField(primary_key=True, serialize=False)),
                ('program_name', models.CharField(max_length=255)),
                ('short_name', models.CharField(max_length=100)),
                ('dept_id', models.ForeignKey(db_column='dept_id', on_delete=django.db.models.deletion.CASCADE, to='CUSTApp.department')),
            ],
            options={
                'db_table': 'program',
            },
        ),
    ]
