# Generated by Django 4.1.13 on 2025-05-02 16:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CUSTApp', '0006_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='signature',
            field=models.FileField(blank=True, null=True, upload_to='media', validators=[django.core.validators.validate_image_file_extension]),
        ),
    ]
