# Generated by Django 4.1.13 on 2025-05-03 15:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CUSTApp', '0007_users_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to='media', validators=[django.core.validators.validate_image_file_extension]),
        ),
    ]
