# Generated by Django 4.1.13 on 2025-05-14 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CUSTApp', '0008_alter_users_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='uu_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
