# Generated by Django 4.1.13 on 2025-05-14 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CUSTApp', '0009_alter_users_uu_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
