# Generated by Django 4.1.13 on 2025-05-15 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CUSTApp', '0010_alter_users_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='dept_name',
        ),
        migrations.AddField(
            model_name='users',
            name='dept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='CUSTApp.department'),
        ),
    ]
