# Generated by Django 4.1.13 on 2025-06-02 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CUSTApp', '0011_remove_users_dept_name_users_dept'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='auth_method',
            field=models.CharField(choices=[('email', 'Email'), ('phone', 'Phone')], default='email', max_length=10),
        ),
    ]
