# Generated by Django 4.1.13 on 2025-06-12 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CUSTApp', '0013_alter_users_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='profile_completed',
            field=models.BooleanField(default=False),
        ),
    ]
