# Generated by Django 4.1.13 on 2025-06-13 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CUSTApp', '0014_users_profile_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='guest_fcm_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
