# Generated by Django 4.1.13 on 2025-06-15 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CUSTApp', '0015_users_guest_fcm_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='program', to='CUSTApp.program'),
        ),
    ]
