# Generated by Django 4.1.13 on 2025-06-15 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CUSTApp', '0016_users_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='passport_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
