# Generated by Django 4.1.13 on 2025-07-31 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CUSTApp', '0017_users_passport_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Convocation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('academic_year', models.CharField(max_length=20)),
                ('registration_date', models.DateField()),
                ('registration_deadline', models.DateField()),
                ('rehearsal_date', models.DateField()),
                ('rehearsal_time', models.TimeField()),
                ('registration_form_link', models.URLField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Upcoming', 'Upcoming'), ('Completed', 'Completed')], default='Upcoming', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'convocations',
                'ordering': ['-created_at'],
            },
        ),
    ]
