# Generated by Django 4.1.13 on 2025-07-31 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CUSTApp', '0018_convocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='convocation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CUSTApp.convocation'),
        ),
        migrations.AddField(
            model_name='users',
            name='secondary_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
