# Generated by Django 4.1.13 on 2025-08-04 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CUSTApp', '0019_users_convocation_users_secondary_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='convocation',
            name='convocation_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
