# Generated by Django 4.1.13 on 2025-08-06 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CUSTApp', '0020_convocation_convocation_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='convocation',
            name='registration_form_link',
        ),
    ]
