# Generated by Django 4.1.13 on 2025-08-06 07:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CUSTApp', '0021_remove_convocation_registration_form_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='signature',
            field=models.FileField(blank=True, null=True, upload_to='profile_pictures', validators=[django.core.validators.validate_image_file_extension]),
        ),
    ]
