# Generated by Django 4.1.13 on 2025-08-06 08:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CUSTApp', '0022_alter_users_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to='profile_pictures', validators=[django.core.validators.validate_image_file_extension]),
        ),
        migrations.AlterField(
            model_name='users',
            name='signature',
            field=models.FileField(blank=True, null=True, upload_to='signatures', validators=[django.core.validators.validate_image_file_extension]),
        ),
    ]
